name: file_system_access_api
description: A Dart library to expose the File System Access Api from web platform.
version: 1.0.1
homepage: https://github.com/poirierlouis/file_system_access_api/

environment:
  sdk: '>=2.18.4 <3.0.0'

platforms:
  web:

dependencies:
  js: ^0.6.4

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  lints: ^2.0.0
  test: ^1.16.0
  webdev: ^2.7.12
